export const RB_GREEN = '#4cc912'
export const RB_LIGHT_GREEN = '#bddebd'
export const RB_BLUE = '#0911ed'
export const RB_WHITE = '#ffffff'
export const RB_TEXT = '#686868'
export const RB_PINK = 'pink'
